name: env multi stage

on:
  workflow_dispatch:
    

jobs:
  staging:
    runs-on: ubuntu
    environment: staging
    steps:
      - name: echo
        run: |
         echo "stagging done"
         sleep 10
  deploy:
    runs-on: ubuntu-latest
    needs: staging
    environment: PROD
    steps:
      - name: echo
        run: echo "deployed to prod"