name: execution

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 
        run: echo "i am job1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo " i am job2"
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "i am job3"
     