name: outputs

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.Status }}
    steps:
      - name: printing path of github output
        run: echo "$GITHUB_OUTPUT"
      - name: build-putput
        id: build
        run: echo "Status=success" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploying output
        run: echo "${{ needs.build.outputs.build-status}}"