name: inputs

on: 
  workflow_dispatch:
    inputs:
      input1:
        type: boolean
        description: say yes or no
        default: false
      input2:
        type: environment
        required: true
        description: which enviroment to deploy
        default: stage
      input3:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello world"

