name: reusable workflow

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build-status:
        description: the value of build process
        value: ${{jobs.deploy.outputs.build-status}}
      url:
        description: the value of url deployed version
        value: ${{jobs.deploy.outputs.url}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.build-status}}
      url: ${{steps.deploy.outputs.url}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build
        id: build
        run: |
         echo "building on ${{inputs.target-directory}}"
         echo "build-status=SUCCESS" >> "$GITHUB_OUTPUT"
      - name: deploy
        id: deploy
        run: |
         echo "url=www.google.com" >> "$GITHUB_OUTPUT"