name: caching

on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: use cache or not
        type: boolean
        default: true

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: caching/react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: download cache
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
           path: caching/react-app/node_modules
           key: deps-node-modules-${{ hashFiles('caching/react-app/package-lock.json')}}
      - name: install dependenices
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: testing
        run: npm run test
      - name: building
        run: npm run build
      - name: deploy
        run: echo "deployed to pod"
