name: reusable workflow

on: 
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/one.yml
    with:
      target-directory: dummy dir
  print-output:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: print outputs
        run: |
         echo "build status: ${{needs.deploy.outputs.build-status }}"
         echo "url: ${{needs.deploy.outputs.url}}"